---
# End tasks

- name: reload toadfarm
  command: "/bin/env /home/{{ ssh_user }}/git/perlbrew-cron/perlbrew-cron.sh script/toadfarm.pl reload"
  become: yes
  become_user: www
  tags: [git,perl,perlbrew,nginx]
  args:
    chdir: /home/{{ ssh_user }}/git/webserver/
# PERLBREW_ROOT=/opt/perl5 PERLBREW_HOME=/home/www/.perlbrew PATH=$PATH:/usr/local/bin

- name: reload hypnotoad
  command: "/bin/env /home/{{ ssh_user }}/git/perlbrew-cron/perlbrew-cron.sh reload-hypnotoads.pl"
  become: yes
  become_user: www
  tags: [git,perl,perlbrew,nginx]
  args:
    chdir: /home/{{ ssh_user }}/git/nginx-security/
