---
- name: Copy file with owner and permissions
  copy:
    src: mojoapp.yml
    dest: /home/www/etc/mojoapp.yml
    owner: www
    group: www
    mode: '0644'
  become: true
  become_user: www
# End tasks

- cron:
    name: "certbot renew"
    minute: "39"
    hour: "19"
    job: "/usr/bin/bash -l -c '/usr/bin/certbot renew'  2>&1 |/home/{{ ssh_user }}/git/utilities-perl/bin/alert.pl"
  become: true
  tags: [nginx]

- cron:
    name: "auto reload webserver"
    minute: "40"
    hour: "1"
    job: "/home/{{ ssh_user }}/git/nginx-security/bin/reload-hypnotoads.pl >>~/log/crontab/toadfarm.log"
  become: true
  become_user: www
  tags: [nginx]

- cron:
    name: "Alert if not messages from pi"
    minute: "40"
    hour: "16"
    job: "/home/{{ ssh_user }}/git/webserver/bin/uptime-pi-alert.pl 2>&1 | /home/{{ ssh_user }}/git/perlbrew-cron/perlbrew-cron.sh /home/{{ ssh_user }}/git/utilities-perl/bin/alert.pl"
  become: true
  become_user: www
  tags: [nginx]


- name: update git
  command: "/usr/bin/env /home/{{ ssh_user }}/git/utilities-perl/bin/git-status --silence"
  tags: [git,perl,perlbrew,nginx,mojo]
#  args:
#    chdir: /home/{{ ssh_user }}/git/nginx-security/


- name: reload hypnotoad
  command: "/usr/bin/env bin/reload-hypnotoads.pl"
  become: yes
  become_user: www
  tags: [git,perl,perlbrew,nginx,mojo]
  args:
    chdir: /home/{{ ssh_user }}/git/nginx-security/

