---
# End tasks

- name: Load vars from nginx
  include_vars:
    dir: roles/nginx/vars/

- template: src=hypnotoad.yml.j2 dest=/home/www/etc/hypnotoad.yml owner=www group=www mode=0644
  become: yes
  become_user: www

- name: reload toadfarm
  command: "/bin/env /home/{{ ssh_user }}/git/perlbrew-cron/perlbrew-cron.sh script/toadfarm.pl reload"
  become: yes
  become_user: www
  tags: [git,perl,perlbrew,nginx]
  args:
    chdir: /home/{{ ssh_user }}/git/webserver/
# PERLBREW_ROOT=/opt/perl5 PERLBREW_HOME=/home/www/.perlbrew PATH=$PATH:/usr/local/bin

- name: reload hypnotoad
  command: "/bin/env /home/{{ ssh_user }}/git/perlbrew-cron/perlbrew-cron.sh reload-hypnotoads.pl"
  become: yes
  become_user: www
  tags: [git,perl,perlbrew,nginx]
  args:
    chdir: /home/{{ ssh_user }}/git/nginx-security/
